# Generated by Django 4.0 on 2022-02-04 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='thickness',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, verbose_name='Толщина'),
        ),
    ]
