# Generated by Django 4.0.1 on 2022-04-16 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='postal_code',
        ),
        migrations.AddField(
            model_name='order',
            name='number',
            field=models.CharField(default=380996602621, max_length=18, verbose_name='Номер'),
            preserve_default=False,
        ),
    ]
